<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["staff", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create staff
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "staff/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldFname" class="col-sm-2 control-label">Fname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["Fname", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldFname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLname" class="col-sm-2 control-label">Lname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["Lname", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldLname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCategory" class="col-sm-2 control-label">Category</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["category", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldCategory"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["username", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldUsername"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["password", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
