
<div id="map"></div>
<div id="message"></div>
     
<script>
    var map;
    var marker;
    var messagewindow;
    
   function initMap() {
    var directionsService = new google.maps.DirectionsService;
    var directionsDisplay = new google.maps.DirectionsRenderer;
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 6,
      center: {lat: 41.85, lng: -87.65}
    });
    directionsDisplay.setMap(map);
  
    $(document).ready(function() {
      calculateAndDisplayRoute(directionsService, directionsDisplay);
    });
   }
   
   function calculateAndDisplayRoute(directionsService, directionsDisplay) {
        var waypts = [];
        var checkboxArray = [ new google.maps.LatLng(18.805197, 98.950159),
                              new google.maps.LatLng(18.806627, 98.951927)];
        for (var i = 0; i < checkboxArray.length; i++) {
            waypts.push({
              location: checkboxArray[i],
              stopover: true
            });
        }
        directionsService.route({
          origin: {lat: 18.804423, lng: 98.947822},
          destination:{lat: 18.808335, lng: 98.954763},
          waypoints: waypts,
          optimizeWaypoints: true,
          travelMode: 'WALKING',
        }, function(response, status) {
          if (status === 'OK') {
            directionsDisplay.setDirections(response);
            var route = response.routes[0];
          } else {
            window.alert('Directions request failed due to ' + status);
          }
        });
   }

   function downloadUrl(url, callback) {
     var request = window.ActiveXObject ?
         new ActiveXObject('Microsoft.XMLHTTP') :
         new XMLHttpRequest;

     request.onreadystatechange = function() {
       if (request.readyState == 4) {
         request.onreadystatechange = doNothing;
         callback(request.responseText, request.status);
       }
     };

     request.open('GET', url, true);
     request.send(null);
   }

   
   function doNothing () {
   }

</script>