<!doctype html>
<html lang="en">

<head>
  <!-- Vue.js -->
  <script src="https://unpkg.com/vue"></script>
  <title></title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Marathon</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
            integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
            crossorigin="anonymous">
    <style>
       #map {
        height: 100vh;
        width: 100%;
       }
    </style>
        <?php $this->assets->outputCss(); ?>
    </head>
    <body>
        <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>



  <nav class="navbar navbar-expand-lg navbar-light bg-light login" style="background-color: #ab5cef !important; ">
    <a class="navbar-brand" style="width:100px;" href="/Marathon/marathon" ><img src="https://www.cmu-marathon.com/uploads/15073558201.png"  style="width:80%"></a>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto" >

        <li class="nav-item">
          <a class="nav-link active" style="color:white;" href="/Marathon/marathon/emergencyreport/">Emergency</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active"style="color:white;"  href="/Marathon/marathon/problemreport/" >Problem</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active  " style="color:white;" href="/Marathon/marathon/runner/" >Runner</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active " style="color:white;" href="/Marathon/marathon/staff/" >Staff</a>
        </li>
      </ul>
      <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex ">
          <a href="/Marathon/marathon/authen/logout" style="color:white;  border-bottom-style: solid; border-width: 1px; border-bottom-color:white;" href="">Log Out</a>
      </ul>
    </div>
  </nav>



</header>


        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>
        <?php $this->assets->outputJs(); ?>
        <script async defer
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCtqbWpbRjhWyJ7Eme-ZRHQWX-4yozoG_g&callback=initMap">
        </script>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </body>
</html>
