<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<link href="https://fonts.googleapis.com/css?family=Kanit" rel="stylesheet">
<style>
body{
  font-family: 'Kanit', sans-serif;
}
</style>
<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "problemreport/create",
            "autocomplete" => "off",
            "style" => "width:100%"

        ]
    );
?>
     <div class="row" style="margin-top: 2%;">
     <div id="map" style="margin-left: 0%; box-shadow: 0px 0px 4px 0px;" class="col-md-8"></div>
 <div class="col-md-4">
     <label for="fieldHeader" class="col-sm-4 control-label" >Title</label>

         <?php echo $this->tag->textArea(["header", "cols" => 30, "rows" => 4, "class" => "form-control ", "id" => "fieldHeader"]) ?>


     <label for="fieldDetail" class="col-sm-4 control-label" >Detail</label>

         <?php echo $this->tag->textArea(["detail", "cols" => 30, "rows" => 4, "class" => "form-control ", "id" => "fieldDetail"]) ?>

     <?php $id = $this->session->get('id');?>

         <?php echo $this->tag->hiddenField(["senderId", "type" => "number", "class" => "form-control ", "id" => "fieldSenderid","value" => "$id"]) ?>

         <?php echo $this->tag->hiddenField(["lag", "size" => 30, "class" => "form-control", "id" => "fieldLag"]) ?>

         <?php echo $this->tag->hiddenField(["lng", "size" => 30, "class" => "form-control", "id" => "fieldLng"]) ?>
     <div class="col-md-5" style="padding:0;margin-top:10px">
                        <select class="form-control mr-sm-2" name="category" id="fieldcategory">
                    <option value="">Category</option>
                    <option value="water">Water point</option>
                    <option value="checkpoint">Check point</option>
                    <option value="toilet">Toilet</option>
                </select>
                </div>
     <div class="col-md-5"  style="padding:0;margin-top:10px">
     <div class="radio">
     <label><input type="radio" name="level" value="1" checked>level 1</label>
   </div>
   <div class="radio">
     <label><input type="radio" name="level" value="2">level 2</label>
   </div>
   <div class="radio ">
     <label><input type="radio" name="level" value="3">level 3</label>
   </div>
   </div>
         <?php echo $this->tag->submitButton(["Save", "class" => "form-control btn btn-default w3-btn w3-white w3-border-red w3-round-large ", ]) ?>
   </div>

<?php echo $this->tag->endForm(); ?>

<style>
    #map{
        height: 500px;
        width: 500px;
    }
    </style>



<script>
    var map;
    var checkMarker = 0;
    var marker;

    function initMap() {
        var myLatLng = {lat: 18.805197, lng: 98.947822};
        var directionsService = new google.maps.DirectionsService;
        var directionsDisplay = new google.maps.DirectionsRenderer;
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: myLatLng
        });
        navigator.geolocation.getCurrentPosition(function(position) {
            console.log(position.coords.latitude);
            marker = new google.maps.Marker({
                    position: new google.maps.LatLng(position.coords.latitude, 
                                                    position.coords.longitude),
                    map: map
                });
            });
        google.maps.event.addListener(map, 'click', function(event) {
            if(checkMarker == 0){
                setMapOnAll(null);
                marker = new google.maps.Marker({
                    position: event.latLng,
                    map: map
                });
                document.getElementById("fieldLag").value =  event.latLng.lat();
                document.getElementById("fieldLng").value =  event.latLng.lng();
                checkMarker = 1;
            }else{
                setMapOnAll(null);
                marker = new google.maps.Marker({
                    position: event.latLng,
                    map: map
                });
                document.getElementById("fieldLag").value =  event.latLng.lat();
                document.getElementById("fieldLng").value =  event.latLng.lng();
            }
        });
        directionsDisplay.setMap(map);
        $(document).ready(function() {
            calculateAndDisplayRoute(directionsService, directionsDisplay);
        });
    }

    function setMapOnAll(map) {
          marker.setMap(map);
    }

    function calculateAndDisplayRoute(directionsService, directionsDisplay) {
        var waypts = [];
        var checkboxArray = [ new google.maps.LatLng(18.808265, 98.954752),
                              new google.maps.LatLng(18.800597, 98.951306),
                              new google.maps.LatLng(18.795357, 98.961808),
                              new google.maps.LatLng(18.805465, 98.960038),
                              new google.maps.LatLng(18.808265, 98.954752)];
        for (var i = 0; i < checkboxArray.length; i++) {
            waypts.push({
              location: checkboxArray[i],
              stopover: true
            });
        }
        directionsService.route({
          origin: {lat: 18.808265, lng: 98.954752},
          destination:{lat: 18.808265, lng: 98.954752},
          waypoints: waypts,
          optimizeWaypoints: true,
          travelMode: 'WALKING',
        }, function(response, status) {
          if (status === 'OK') {
            directionsDisplay.setDirections(response);
            var route = response.routes[0];
          } else {
            window.alert('Directions request failed due to ' + status);
          }
        });
   }

   function downloadUrl(url, callback) {
     var request = window.ActiveXObject ?
         new ActiveXObject('Microsoft.XMLHTTP') :
         new XMLHttpRequest;

     request.onreadystatechange = function() {
       if (request.readyState == 4) {
         request.onreadystatechange = doNothing;
         callback(request.responseText, request.status);
       }
     };

     request.open('GET', url, true);
     request.send(null);
   }

   
   function doNothing () {
   }

</script>

<style>
  .boxheader{
    box-shadow: 0px 0px 4px 0px;
    margin-left: 163%;
    margin-top: 7%;
    position: absolute;
    line-height: 0.5;
    width: 100%;
    padding: .375rem .75rem;
    font-size: 1rem;
    color: #495057;
    background-color: #fff;
    background-image: none;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: .25rem;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;

  }
  .bdetail{
    box-shadow: 0px 0px 4px 0px;
    margin-left: 163%;
    margin-top: -96%;
    position: absolute;
  }
  .brun{
    box-shadow: 0px 0px 4px 0px;
    margin-left: 163%;
    margin-top: -66%;
    position: absolute;
  }
  .bstaf{
    box-shadow: 0px 0px 4px 0px;
    margin-left: 163%;
    margin-top: -55%;
    position: absolute;
  }
  .bla{
   box-shadow: 0px 0px 4px 0px;
    margin-left: 163%;
    margin-top: -52%;
    position: absolute;

  }
</style>
