<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>


<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "problemreport/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>
<div class="container" style=" padding-top: 12%;">
      <div class="form-group">
          <label for="fieldHeader" class="col-sm-2 control-label"  style="    position: absolute;  margin-top: 2%;  margin-left: 41%; ">Header</label>
          <div class="col-sm-10">
              <?php echo $this->tag->textArea(["header", "cols" => 30, "rows" => 4, "class" => "boxheader", "id" => "fieldHeader"]) ?>
          </div>
      </div>

      <div id="map" style="margin-left: 4%; box-shadow: 0px 0px 4px 0px;"></div>

      <div class="form-group">
          <label for="fieldDetail" class="col-sm-2 control-label" style="position: absolute; margin-top: -28%;  margin-left: 41%; ">Detail</label>
          <div class="col-sm-10">
              <?php echo $this->tag->textArea(["detail", "cols" => 30, "rows" => 4, "class" => "form-control bdetail", "id" => "fieldDetail"]) ?>
          </div>
      </div>

      <div class="form-group">
          <label for="fieldSenderid" class="col-sm-2 control-label" style="    position: absolute;  margin-top: -19%;  margin-left: 41%;">Sender ID</label>
          <div class="col-sm-10">
              <?php echo $this->tag->textField(["senderId", "type" => "number", "class" => "form-control brun", "id" => "fieldSenderid"]) ?>
          </div>
      </div>

      <div class="form-group">
          <label for="fieldStaffid" class="col-sm-2 control-label" style="    position: absolute;  margin-top: -16%;  margin-left: 41%;">Staff ID </label>
          <div class="col-sm-10">
              <?php echo $this->tag->textField(["staffId", "type" => "number", "class" => "form-control bstaf", "id" => "fieldStaffid"]) ?>
          </div>
      </div>

      <div class="form-group">
          <div class="col-sm-10">
              <?php echo $this->tag->hiddenField(["lag", "size" => 30, "class" => "form-control", "id" => "fieldLag"]) ?>
          </div>
      </div>

      <div class="form-group">
          <div class="col-sm-10">
              <?php echo $this->tag->hiddenField(["lng", "size" => 30, "class" => "form-control", "id" => "fieldLng"]) ?>
          </div>
      </div>

      <div class="form-group">
          <label for="fieldLevel" class="col-sm-2 control-label" style="    position: absolute;  margin-top: -15%;  margin-left: 41%;">Level</label>
          <div class="col-sm-10">
              <?php echo $this->tag->textField(["level", "type" => "number", "class" => "form-control bla", "id" => "fieldLevel"]) ?>
          </div>
      </div>


      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
              <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default w3-btn w3-white w3-border-red w3-round-large", "style" => " margin-left: 192%; margin-top: -40%; width: 36%; position: absolute; "]) ?>
          </div>
      </div>
  </div>
<?php echo $this->tag->endForm(); ?>

<style>
    #map{
        height: 500px;
        width: 500px;
    }
    </style>



<script>
    var map;
    var checkMarker = 0;
    var marker;

    function initMap() {
        var myLatLng = {lat: 18.805197, lng: 98.947822};

        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: myLatLng
        });

        google.maps.event.addListener(map, 'click', function(event) {
            if(checkMarker == 0){
                marker = new google.maps.Marker({
                    position: event.latLng,
                    map: map
                });
                document.getElementById("fieldLag").value =  event.latLng.lat();
                document.getElementById("fieldLng").value =  event.latLng.lng();
                checkMarker = 1;
            }else{
                setMapOnAll(null);
                marker = new google.maps.Marker({
                    position: event.latLng,
                    map: map
                });
                document.getElementById("fieldLag").value =  event.latLng.lat();
                document.getElementById("fieldLng").value =  event.latLng.lng();
            }
        });
    }

    function setMapOnAll(map) {
          marker.setMap(map);
    }


</script>

<style>
  .boxheader{
    box-shadow: 0px 0px 4px 0px;
    margin-left: 163%;
    margin-top: 7%;
    position: absolute;
    line-height: 0.5;
    width: 100%;
    padding: .375rem .75rem;
    font-size: 1rem;
    color: #495057;
    background-color: #fff;
    background-image: none;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: .25rem;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;

  }
  .bdetail{
    box-shadow: 0px 0px 4px 0px;
    margin-left: 163%;
    margin-top: -96%;
    position: absolute;
  }
  .brun{
    box-shadow: 0px 0px 4px 0px;
    margin-left: 163%;
    margin-top: -66%;
    position: absolute;
  }
  .bstaf{
    box-shadow: 0px 0px 4px 0px;
    margin-left: 163%;
    margin-top: -55%;
    position: absolute;
  }
  .bla{
   box-shadow: 0px 0px 4px 0px;
    margin-left: 163%;
    margin-top: -52%;
    position: absolute;

  }
</style>
