
<!doctype html>
<html lang="en">

<head>
  <!-- Vue.js -->
  <script src="https://unpkg.com/vue"></script>
  <title></title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>

<body>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>




<style>
.container {
    margin-top: 10px;
    text-align: center;
}
.search {
    margin-top: 30px;
    margin-left: 18px;
}
.add{
  margin-left: 10px;
}
</style>


<div class="page-header">
<div class="search">
<form class=" form-inline my-2 my-lg-0" action ="../problemreport/search" method="POST">
<input class="form-control mr-sm-2" type="search" placeholder="Title" aria-label="Search"name="header">

  <input class="form-control mr-sm-2" type="search" placeholder="Staff" aria-label="Search"name="staffId">
  <select class="form-control mr-sm-2" name="level" id="">
    <option value="">Select level</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
</select>
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    <button class="add btn btn-outline-success my-2 my-sm-0" ><a href="/Marathon/marathon/problemreport/new/" style="color:#28a745;">Add</a></button>
</form>
</div>
</div>

<?php echo $this->getContent(); ?>

<!-- ข้อมูล -->
<div class="container"  id="example-1">

  <table class="w3-table-all">
     <thead>
       <tr style="background-color: black; color:white;">
         <th>Id</th>
         <th>Title</th>
         <th>Staff Name</th>
         <th>Level</th>
         <th>View</th>
       </tr>
     </thead>

     <tbody>
     <?php if(isSet($page)){
     foreach ($page->items as $problemreport): ?>
         <tr class="w3-hover-red">
         <td><?php echo $problemreport->id ?></td>
         <td><?php echo $problemreport->header ?></td>
         <td><?php echo $problemreport->staffId ?></td>
         <td><?php echo $problemreport->level ?></td>

             <td><a href="/Marathon/marathon/problemreport/edit/<?php echo $problemreport->id ?>">View</td>
         </tr>
     <?php endforeach;
     } ?>
     </tbody>


   </table>
</div>

<!-- เเถบเลื่อนหน้า -->
<div class="container">
    <ul class="pager">
      <li class="w3-btn " style="margin-left: 10px;">
          <?php echo $page->current, "/", $page->total_pages ?>
      </li>
     <a href="/Marathon/marathon/problemreport/search?page=<?php echo $page->next ?>"><li class="w3-btn w3-white w3-border w3-border-black  w3-round-xxlarge " style="float: right; color:white !important; background-color: black !important;"><h5> ></h5> </li></a>
     <a href="/Marathon/marathon/problemreport/search?page=<?php echo $page->before ?>"><li class="w3-btn w3-white w3-border  w3-border-black  w3-round-xxlarge w3-left" style="margin-left: -40px; color:white !important; background-color: black !important;" > <h5> <</h5>  </li></a>
 </ul>
</div>
</html>
