<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["problemreport/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["problemreport/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Header</th>
            <th>Detail</th>
            <th>SenderId</th>
            <th>StaffId</th>
            <th>Lag</th>
            <th>Lng</th>
            <th>Status</th>
            <th>Level</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $problemreport): ?>
            <tr>
                <td><?php echo $problemreport->id ?></td>
            <td><?php echo $problemreport->header ?></td>
            <td><?php echo $problemreport->detail ?></td>
            <td><?php echo $problemreport->senderId ?></td>
            <td><?php echo $problemreport->staffId ?></td>
            <td><?php echo $problemreport->lag ?></td>
            <td><?php echo $problemreport->lng ?></td>
            <td><?php echo $problemreport->status ?></td>
            <td><?php echo $problemreport->level ?></td>

                <td><?php echo $this->tag->linkTo(["problemreport/edit/" . $problemreport->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["problemreport/delete/" . $problemreport->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("problemreport/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("problemreport/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("problemreport/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("problemreport/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
