
<!doctype html>
<html lang="en">

<head>
  <!-- Vue.js -->
  <script src="https://unpkg.com/vue"></script>
  <title></title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>

<body>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>




<style>
.container {
    margin-top: 10px;
    text-align: center;
}
.search {
    margin-top: 30px;
    margin-left: 18px;
}
.add{
  margin-left: 10px;
}
.card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    max-width: 300px;
    margin: auto;
    text-align: center;
}

.title {
    color: Black;
    font-size: 18px;
}

.media {
    text-decoration: none;
    font-size: 25px !important;
    color: black;
    width: 20px;
    height: 32px;

}
.social{
  text-align: center;
  float: left;
  width: 50%;

}
.name{
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: black;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}
.photo{
  height: 300px;
}

button:hover, a:hover {
    opacity: 0.7;
}
.select{
  color: black !important;
  border-color: black !important;
}
</style>


<div class="page-header">
<div class="search">
<form class=" form-inline my-2 my-lg-0" action ="../problemreport/search" method="POST">
<input class="form-control mr-sm-2" type="search" placeholder="Title" aria-label="Search"name="header">

  <input class="form-control mr-sm-2" type="search" placeholder="Staff" aria-label="Search"name="staffId">
  <select class="form-control mr-sm-2" name="level" id="">
    <option value="">Select level</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
</select>
<select class="form-control mr-sm-2" name="category" id="">
    <option value="">Category</option>
    <option value="water">Water point</option>
    <option value="checkpoint">Check point</option>
  </select>
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  <a href="/Marathon/marathon/problemreport/new/" style="color:#28a745;"><button class="add btn btn-outline-success my-2 my-sm-0" >Add</button></a>
</form>
</div>
</div>

<?php echo $this->getContent(); ?>

<!-- ข้อมูล -->
<div class="container"  id="example-1">

  <table class="w3-table-all">
     <thead>
       <tr style="background-color: black; color:white;">
         <th>Id</th>
         <th>Title</th>
          <th>Sender Name</th>
         <th>Category</th>
         <th>Level</th>
         <th>Status</th>
         <th>View</th>
       </tr>
     </thead>

     <tbody>

     <?php if(isSet($page)){
     foreach ($page->items as $problemreport): ?>
         <tr class="w3-hover-red">
         <td><?php echo $problemreport->id ?></td>
         <td><?php echo $problemreport->header ?></td>


          <!--กล่อง pop up sendername -->
         <?php $sendername = Staff::findFirstByid($problemreport->senderId);?>
         <td data-toggle="modal" data-target="#myModal<?php echo $sendername->id ?>"  ><?php echo $sendername->fname." ".$sendername->lname ?></a></td>

         <div class="container">
           <!-- Trigger the modal with a button -->
           <!-- Modal -->
           <div class="modal fade" id="myModal<?php echo $sendername->id ?>" role="dialog">
             <div class="modal-dialog">
               <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
           <div class="card">
           <img src="../public/images/<?php echo $sendername->images ?>"  style="height:270px;">
             <h5 class="name"> <?php echo $sendername->fname." ".$sendername->lname ?></h5>
             <p class="title"> Category : <?php echo $sendername->category ?></p>
           </div>
             </div>
           </div>
         </div>

       <td><?php echo $problemreport->category ?></td>
      
         <td><?php echo $problemreport->level ?></td>
       <td><?php echo $problemreport->status ?></td>
         

             <td><a href="/Marathon/marathon/problemreport/edit/<?php echo $problemreport->id ?>">View</td>
         </tr>
     <?php endforeach;
     } ?>
     </tbody>


   </table>
</div>

<!-- เเถบเลื่อนหน้า -->
<div class="container">
    <ul class="pager">
      <li class="w3-btn " style="margin-left: 10px;">
          <?php echo $page->current, "/", $page->total_pages ?>
      </li>
     <a href="/Marathon/marathon/problemreport/search?page=<?php echo $page->next ?>"><li class="w3-btn w3-white w3-border w3-border-black  w3-round-xxlarge " style="float: right; color:white !important; background-color: black !important;"><h5> ></h5> </li></a>
     <a href="/Marathon/marathon/problemreport/search?page=<?php echo $page->before ?>"><li class="w3-btn w3-white w3-border  w3-border-black  w3-round-xxlarge w3-left" style="margin-left: -40px; color:white !important; background-color: black !important;" > <h5> <</h5>  </li></a>
 </ul>
</div>
</html>
