<?php echo $this->flashSession->output(); ?>

<?php if ($this->session->get('username')!=null&&$this->session->get('password')!=null){ ?>
  <p> session username : <?php echo $this->session->get('username');?> </p>
  <p> session password : <?php echo $this->session->get('password');?> </p>
  <p> session password : <?php echo $this->session->get('id');?> </p>


  <p> cookie username : <?php echo $this->cookies->get('username');?> </p>
  <p> cookie password : <?php echo $this->cookies->get('password');?> </p>

<?php } ?>

<?php
    echo $this->tag->form(
        [
            "Authen/index",
            "autocomplete" => "off",
            "style" => "form-horizontal"
        ]
    );
?>
<body>
<meta name="viewport" content="width=device-width, initial-scale=1">
</body>
<style>

.Remember{
  margin-top: 10px;
  margin-left: 280px;
}
.check{
  margin-left: -15px;
  width: 40px;
}
.container2{
      position: relative;
      top: 10%;
      margin: auto;
      padding: 48px;
      width: 480px;
      background-color: #FFF;
      text-align: center;
      vertical-align: middle;

}
.image{
    margin: auto;
}
.submit{
  margin: 18px 0px 12px 0px;
  height: 32px;
  border-radius: 2px;
  width: 100%;
  color: #FFF;
  background-color: rgba(116, 58, 147, 0.8);
}
body {
background-image: url("http://www.mx7.com/i/2b9/BJSA8D.png");
background-size: cover;
}
</style>
<br>
<br>
<div class="container2">
  <div class="col-md-6 col-sm-6 col-xs-6 image">
      <img src="https://www.cmu-marathon.com/uploads/15073558201.png" style="max-width: 100%; width: auto;height: 60px;text-align: center;">
  </div>
  <br>


<!-- ตรงนี้ -->


      <div class="input-group">
      <?php echo $this->tag->textField(["username", "cols" => 30, "class" => "form-control", "placeholder" => "Username",]) ?>
</div>

<br>


    <div class="input-group">
      <?php echo $this->tag->passwordField(["password", "cols" => 30, "class" => "form-control ", "placeholder" => "Password",]) ?>
  </div>


  <br>
<!-- ถึงตรงนี้ -->

  <div class="form-group text-center">

    <button type="submit" class="btn submit"> Submit </button>
  </div>



<?php echo $this->tag->endForm(); ?>

  </div>
