<?php echo $this->flashSession->output(); ?>

<?php if ($this->session->get('username')!=null&&$this->session->get('password')!=null){ ?>
  <p> session username : <?php echo $this->session->get('username');?> </p>
  <p> session password : <?php echo $this->session->get('password');?> </p>
  <p> session password : <?php echo $this->session->get('id');?> </p>


  <p> cookie username : <?php echo $this->cookies->get('username');?> </p>
  <p> cookie password : <?php echo $this->cookies->get('password');?> </p>

<?php } ?>

<?php
    echo $this->tag->form(
        [
            "Authen/index",
            "autocomplete" => "off",
            "style" => "form-horizontal"
        ]
    );
?>
<body>

</body>
<style>
.textbox{
  width: 500px;
  float: right;
}
.Remember{
  margin-top: 10px;
  margin-left: 280px;
}
.check{
  margin-left: -15px;
  width: 40px;
}
body {
    background-image: url("https://drive.google.com/file/d/1LJnvQqjQhbUS5DXjZbwwhrZdDfOJh-v4/view");
    background-size: 100% auto;
}
</style>
<br>
<br>
<div class="container" style="">
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <div class="input-group">
        <span class="input-group-btn">
          <button class="btn btn-secondary" type="button">Go!</button>
        </span>

      <?php echo $this->tag->textField(["username", "cols" => 30, "class" => "textbox form-control ", "placeholder" => "Username",]) ?>
</div>
    </div>
  </div>
<br>
<div class="row">
  <div class="col-lg-6 offset-lg-3">
    <div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-secondary" type="button">Go!</button>
      </span>
      <?php echo $this->tag->passwordField(["password", "cols" => 30, "class" => "textbox form-control ", "placeholder" => "Password",]) ?>
  </div>
    </div>
  </div>
  <br>

  <div class="form-group offset-lg-3">
     <label for="fieldHeader" class="col-sm-4 control-label" >Remember Me <?php echo " ".$this->tag->checkField(["remember", "class" => "check"]) ?></label>

  </div>

  <div class="form-group text-center">

    <button type="submit" class="btn btn-primary btn-lg"> Submit </button>
    <button type="reset" class="btn btn-danger btn-lg"> Reset </button>
  </div>



<?php echo $this->tag->endForm(); ?>

  </div>
