<?php echo $this->flashSession->output(); ?>

<?php if ($this->session->get('username')!=null&&$this->session->get('password')!=null){ ?>
  <p> session username : <?php echo $this->session->get('username');?> </p>
  <p> session password : <?php echo $this->session->get('password');?> </p>
  <p> session password : <?php echo $this->session->get('id');?> </p>


  <p> cookie username : <?php echo $this->cookies->get('username');?> </p>
  <p> cookie password : <?php echo $this->cookies->get('password');?> </p>

<?php } ?>

<?php
    echo $this->tag->form(
        [
            "Authen/index",
            "autocomplete" => "off",
            "style" => "form-horizontal"
        ]
    );
?>
<style>
.textbox{
  width: 500px;
  float: right;
}
.Remember{
  margin-top: 10px;
  margin-left: 280px;
}
.check{
  margin-left: -15px;
  width: 40px;
}
\
</style>
<br>
<br>
<div class="container" style="">
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <div class="input-group">
        <span class="input-group-btn">
          <button class="btn btn-secondary" type="button">Go!</button>
        </span>

      <?php echo $this->tag->textField(["username", "cols" => 30, "class" => "textbox form-control ", "placeholder" => "Username",]) ?>
</div>
    </div>
  </div>
<br>
<div class="row">
  <div class="col-lg-6 offset-lg-3">
    <div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-secondary" type="button">Go!</button>
      </span>
      <?php echo $this->tag->passwordField(["password", "cols" => 30, "class" => "textbox form-control ", "placeholder" => "Password",]) ?>
  </div>
    </div>
  </div>
  <br>

  <div class="form-group offset-lg-3">
     <label for="fieldHeader" class="col-sm-4 control-label" >Remember Me <?php echo " ".$this->tag->checkField(["remember", "class" => "check"]) ?></label>

  </div>

  <div class="form-group text-center">

    <button type="submit" class="btn btn-primary btn-lg"> Submit </button>
    <button type="reset" class="btn btn-danger btn-lg"> Reset </button>
    <!--<a href="authen/logout" class="btn btn-danger"> Logout </a>-->
  </div>



<?php echo $this->tag->endForm(); ?>

  </div>




<script>
// var access = "";
//
// function getUserData() {
//   $.post("authen/getdatafb", {
//       token: access
//     })
//     .done(function(response) {
//       if (response == "failed") alert("Login Failed.");
//       else if (response == "success") window.location.href = "profile";
//     })
//     .fail(function(response) {
//       console.log("failed");
//       console.log(response);
//     });
// }
//
// function clearSession() {
//   $.post("authen/logout")
//     .done(function(response) {
//       if (response == "failed") alert("Logout Failed.");
//       else if (response == "success") window.location.href = "authen";
//     })
//     .fail(function(response) {
//       console.log("failed");
//       console.log(response);
//     });
// }
//
// window.fbAsyncInit = function() {
//   FB.init({
//     appId: '138619826774612',
//     cookie: true,
//     xfbml: true,
//     autoLogAppEvents: true,
//     status: true,
//     version: 'v2.10'
//   });
//
//   FB.getLoginStatus(function(response) {
//     if (response.status === 'connected') {
//       statusChangeCallback(response);
//     } else {
//
//     }
//   });
// };
//
// function statusChangeCallback(response) {
//   access = response.authResponse.accessToken;
//   if (response.status === 'connected') {
//     getUserData();
//   } else {
//
//   }
// }
//
// (function(d, s, id) {
//   var js, fjs = d.getElementsByTagName(s)[0];
//   if (d.getElementById(id)) {
//     return;
//   }
//   js = d.createElement(s);
//   js.id = id;
//   js.src = "//connect.facebook.com/en_US/sdk.js";
//   fjs.parentNode.insertBefore(js, fjs);
// }(document, 'script', 'facebook-jssdk'));
//
// $(document).on('click', '#loginFacebook', function() {
//   FB.login(function(response) {
//     if (response.authResponse) {
//       access = response.authResponse.accessToken;
//       statusChangeCallback(response);
//     }
//   }, {
//     scope: 'username,public_profile',
//     return_scopes: true
//   });
// });
//
// $(document).on('click', '#logoutFacebook', function() {
//   FB.logout(function(response) {
//     clearSession();
//   });
// });

</script>
