<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search runner
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["runner/new", "Create runner"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "runner/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFname" class="col-sm-2 control-label">Fname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["Fname", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldFname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLname" class="col-sm-2 control-label">Lname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["Lname", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldLname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSsid" class="col-sm-2 control-label">SSID</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["SSID", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldSsid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTel" class="col-sm-2 control-label">Tel</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["Tel", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldTel"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["username", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldUsername"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["Password", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
