<!doctype html>
<html lang="en">

<head>
  <!-- Vue.js -->
  <script src="https://unpkg.com/vue"></script>
  <title></title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>

<body>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  <link href="https://fonts.googleapis.com/css?family=Kanit" rel="stylesheet">
</body>
<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>




<style>
.container {
    margin-top: 10px;
    text-align: center;
}
.search {
    margin-top: 30px;
    margin-left: 18px;
}
.card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    max-width: 300px;
    margin: auto;
    text-align: center;
    background-image: url("http://www.mx7.com/i/2b9/BJSA8D.png");
    background-size: cover;

}

.title {
    color: Black;
    font-size: 18px;
}

.media {
    text-decoration: none;
    font-size: 25px !important;
    color: black;
    width: 20px;
    height: 32px;

}
.social{
  text-align: center;
  float: left;
  width: 50%;

}
.cover{
  position: relative;
  width: 100% ;
  height: 200px;

}
.name{
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  padding-top: 15%;
  color: white;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 25px;
}
.ssid{
  border: none;
  outline: 0;
  display: inline-block;
  color: #ffffff;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 20px;
}
.photo{
  position: absolute;
  height: 100%;
  width: 60%;
  border: 10px solid #ffffff;
  bottom: -23%;
}

button:hover, a:hover {
    opacity: 0.7;
}
.select{
  color: black !important;
  border-color: black !important;
}
p{
  font-size: 18px;
  color: black;
   font-weight: 700;
}

body{
  font-family: 'Kanit', sans-serif;
}
</style>
<div class="col-md-12 text-center" style="color:black;  border-bottom-style: solid; border-width: 1px; border-bottom-color:black;">
  <h1>List of Runner</h1>
</div>
<div class="page-header">
<div class="search">

<form class=" form-inline my-2 my-lg-0" action="../runner/search" method="POST">
<input class="form-control mr-sm-2" type="search" placeholder="Bib id" aria-label="Search" name="id">
<input class="form-control mr-sm-2" type="search" placeholder="First name" aria-label="Search"name="fname">
<input class="form-control mr-sm-2" type="search" placeholder="Last name" aria-label="Search"name="lname">

<select class="form-control mr-sm-2" name="type">
<option value="">Type</option>
<option value="Marathon">Marathon</option>
  <option value="Half">Half-maratho</option>
  <option value="Mini">Mini-marathon</option>
</select>

 <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
</div>
</div>

<?php echo $this->getContent(); ?>

<!-- ข้อมูล -->
<div class="container"  id="example-1">


  <table class="w3-table-all">
     <thead>
       <tr style="background-color: black; color:white;">
       <th>Bib id</th>
       <th>First Name</th>
       <th>Last Name</th>
       <th>Nationality</th>
       <th>Type </th>
       <th>View </th>
       </tr>
     </thead>

     <tbody >
     <?php if(isSet($page)){
         foreach ($page->items as $runner): ?>
            <tr class="w3-hover-">
            <td><?php echo $runner->id ?></td>
            <td><?php echo $runner->fname ?></td>
            <td><?php echo $runner->lname ?></td>
            <td><?php echo $runner->nationality ?></td>
            <td><?php echo $runner->type ?></td>


            <td data-toggle="modal" data-target="#myModal<?php echo $runner->id ?>"  ><a style="color: #0056b3">View</a></td>
            </tr>

            <div class="container">
            <!-- Trigger the modal with a button -->
            <!-- Modal -->
            <div class="modal fade" id="myModal<?php echo $runner->id ?>" role="dialog">
            <div class="modal-dialog">
              <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <div class="card">
            <div class="cover">
              <p class="ssid w3-padding w3-display-topmiddle">RUNNER</p>
              <img  class="rounded-circle photo w3-display-bottommiddle" src="../public/images/<?php echo $runner->images ?>">
            </div>
            <p class="name"><?php echo $runner->fname." ".$runner->lname ?></p>

            <p>Gender : <?php echo $runner->gender?></p>
            <p>Telephone number : <?php echo $runner->tel?></p>
            <p>Nationality : <?php echo $runner->nationality?></p>
            <p>Shirt : <?php echo $runner->shirt?></p>
            </div>
            </div>
            </div>
            </div>



        <?php endforeach;
        } ?>
        </tbody>


   </table>
</div>

<!-- เเถบเลื่อนหน้า -->
<div class="container">
    <ul class="pager">
      <li class="w3-btn " style="margin-left: 10px;">
          <?php echo $page->current, "/", $page->total_pages ?>
      </li>
     <a href="/Marathon/marathon/runner/search?page=<?php echo $page->next ?>"><li class="w3-btn w3-white w3-border w3-border-black  w3-round-xxlarge " style="float: right; color:white !important; background-color: black !important;"><h5> ></h5> </li></a>
     <a href="/Marathon/marathon/runner/search?page=<?php echo $page->before ?>"><li class="w3-btn w3-white w3-border  w3-border-black  w3-round-xxlarge w3-left" style="margin-left: -40px; color:white !important; background-color: black !important;" > <h5> <</h5>  </li></a>
 </ul>
</div>




</html>
