<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["news", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create news
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "news/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldHeader" class="col-sm-2 control-label">Header</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["header", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldHeader"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDetail" class="col-sm-2 control-label">Detail</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["detail", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDetail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAuthor" class="col-sm-2 control-label">Author</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["author", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldAuthor"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
