<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["checkpointreport", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create checkpointreport
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "checkpointreport/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCheckpointid" class="col-sm-2 control-label">CheckpointId</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["checkpointId", "type" => "number", "class" => "form-control", "id" => "fieldCheckpointid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRunnerid" class="col-sm-2 control-label">RunnerId</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["runnerId", "type" => "number", "class" => "form-control", "id" => "fieldRunnerid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTime" class="col-sm-2 control-label">Time</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["time", "size" => 30, "class" => "form-control", "id" => "fieldTime"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
