
<!doctype html>
<html lang="en">

<head>


  <!-- Vue.js -->
  <script src="https://unpkg.com/vue"></script>
  <title>Hello, world!</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

  <style>
        .manuBar{
            background-color: #AB5CEF !important;

        }
        a {
            color: #FFF;
            text-decoration: none;
        }

        .boxmap{
            /* border: 1px solid #000000; */
            /* border: 1px solid #000000; */

            height: 729px !important;
            /* margin: auto !important; */
            /* margin-top: 2% !important; */
            background: rgba(224, 224, 208, 0.1) !important;
            box-shadow: #7d7d7d 0px 1px 5px 1px !important;


        }

        .boxInfor{
            background: rgb(255, 255, 255);
            width: 100%;
            width: 56%;
            height: auto;
            margin: auto;
            margin-top: 1.5%;
            box-shadow: rgba(125, 125, 125, 0.61) 0px 1px 11px 1px;
        }

        .Detaill{
            background: rgba(255, 255, 255, 0.98);
            width: 27%;
            height: 94px!important;
            /* margin: auto; */
            margin-left: 2%;
            margin-top: 3.9%;
            /* margin-top: 0%; */
            box-shadow: rgba(171, 92, 239, 0.49) 1px 1px 4px 1px;
            position: absolute;
        }

        .Fdetail{
            color: #FFF;
            text-decoration: none;
            position: absolute;
            margin-top: 1.5%;
            margin-left: 2%;

        }
        .Frunner{
            color: #FFF;
            text-decoration: none;
            position: absolute;
            margin-top: 4.5%;
            margin-left: 30%;

        }
        .Flevel{
            color: #FFF;
            text-decoration: none;
            position: absolute;
            margin-top: 6%;
            margin-left: 30%;

        }
        .Fstaff{
            color: #FFF;
            text-decoration: none;
            position: absolute;
            margin-top: 7.7%;
            margin-left: 30%;

        }
        .edit{
            margin-left: 2%;
            margin-top: 11%;
            width: 14%;
            height: 36px;
            position: fixed;
            padding-left: 1%;
        }

  </style>
</head>

<body>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCvqrmo8JMF8z0iWYiUPhrj9_imUI6exyU&callback=initMap">
  </script>
</body>



<div id="map" class="boxmap  col-md-8"> </div>

<div class=" form-group col-md-4 w3-padding-16">
  <?php
  $staff = Staff::findFirstByid($this->tag->getValue("staffId"));
  $runner = Runner::findFirstByid($this->tag->getValue("runnerId"));

  ?>
  <div class="col-md-10 w3-padding-16" style="color:black; box-shadow: rgba(125, 125, 125, 0.65) 0px 0px 10px 0px; height: 25%;">
    <div  style="background:#ab5cef; width:7%; height:29%; float: left;"></div>
    <div ><h3  style="border-bottom-style: solid; border-width: 2px; border-bottom-color:#ab5cef; padding-left: 10%;">TITLE</h3></div>
    <p><?php echo $this->tag->getValue("header"); ?></p>
  </div>
  <p>
    <div class="col-md-10 w3-padding-16" style="color:black; box-shadow: rgba(125, 125, 125, 0.65) 0px 0px 10px 0px; height: 25%;">
    <div  style="background:#ab5cef; width:7%!important; height:29%!important; float: left!important;"></div>
    <div> <h3 style="border-bottom-style: solid; border-width: 2px; border-bottom-color:#ab5cef;padding-left: 10%;">DETAIL</h3></div>
      <p> <?php echo $this->tag->getValue("detail"); ?></p>

    </div>
<p>
<div class="col-md-10 w3-padding-16" style="color:black; box-shadow: rgba(125, 125, 125, 0.65) 0px 0px 10px 0px; height: 48%;">
  <div  style="background:#ab5cef; width:7%; height:13%!important; float: left;"></div>
    <div><h3 style="border-bottom-style: solid; border-width: 2px; border-bottom-color:#ab5cef;padding-left: 10%;">MORE DETAIL</h3></div>
  <span>Runner : <?php echo $runner->fname." ".$runner->lname; ?></span>
  <br>
  <span>Staff : <?php echo $staff->fname." ".$staff->lname; ?></span>
    <p>Level : <?php echo $this->tag->getValue("level"); ?></p>

        <?php
         $status = $this->tag->getValue("status");
            if($status == 0){
                $id = $this->tag->getValue("id");
                
                    echo $this->tag->form(
                        [
                            "emergencyreport/done/$id",
                            "autocomplete" => "off",
                            "style" => "width:100%"
                
                        ]
                    );
               echo $this->tag->hiddenField(["id", "type" => "number", "class" => "form-control ", "id" => "fieldId","value" => "$id"]);
               echo $this->tag->hiddenField(["status", "type" => "number", "class" => "form-control ", "id" => "fieldStatus","value" => "1"]) ?>

              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Done</button>
  
                <?php echo $this->tag->endForm();} ?>
</div>
</div>




<script>
function initMap() {
   var uluru = {lat:   <?php echo $this->tag->getValue("lag"); ?> , lng: <?php echo $this->tag->getValue("lng"); ?>};
   var map = new google.maps.Map(document.getElementById('map'), {
         zoom: 16,
         center: uluru,
        streetViewControl: false,
        mapTypeControl: false,
        fullscreenControl: false
   });
   var marker = new google.maps.Marker({
         position: uluru,
         map: map

   });
}

</script>


</html>
