
<!doctype html>
<html lang="en">

<head>
  <!-- Vue.js -->
  <script src="https://unpkg.com/vue"></script>
  <title></title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>

<body>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>




<style>
.container {
    margin-top: 10px;
    text-align: center;
}
.search {
    margin-top: 30px;
    margin-left: 18px;
}
.card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    max-width: 300px;
    margin: auto;
    text-align: center;
    background-image: url("http://www.mx7.com/i/2b9/BJSA8D.png");
    background-size: cover;

}

.title {
    color: Black;
    font-size: 18px;
}

.media {
    text-decoration: none;
    font-size: 25px !important;
    color: black;
    width: 20px;
    height: 32px;

}
.social{
  text-align: center;
  float: left;
  width: 50%;

}
.cover{
  position: relative;
  width: 100% ;
  height: 200px;

}
.name{
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  padding-top: 15%;
  color: white;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 25px;
}
.ssid{
  border: none;
  outline: 0;
  display: inline-block;
  color: #ffffff;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 20px;
}
.photo{
  position: absolute;
  height: 100%;
  width: 60%;
  border: 10px solid #ffffff;
  bottom: -23%;
}

button:hover, a:hover {
    opacity: 0.7;
}
.select{
  color: black !important;
  border-color: black !important;
}
p{
  font-size: 18px;
  color: black;
   font-weight: 700;
}
.add{
 margin-left: 10px;
}
.star-rating {   /* เพิ่ม*/
  font-size:17px;
}

</style>
<div class="col-md-12 text-center" style="color:black;  border-bottom-style: solid; border-width: 1px; border-bottom-color:black;">
  <h1>List of Emergemcy</h1>
</div>
<div class="page-header">
<div class="search">
<form class=" form-inline my-2 my-lg-0" action ="../emergencyreport/search" method="POST">
<input class="form-control mr-sm-2" type="search" placeholder="Title" aria-label="Search"name="header">

<select class="form-control mr-sm-2" name="level" id="">
    <option value="">Select level</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
</select>
<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
<a href="/Marathon/marathon/emergencyreport/new/" style="color:#28a745;"> <div class="add btn btn-outline-success my-2 my-sm-0" >Add</div></a>

</form>




</div>
</div>

<?php echo $this->getContent(); ?>

<!-- ข้อมูล -->
<div class="container"  id="example-1">

  <table class="w3-table-all">
     <thead>
       <tr style="background-color: black; color:white; ">
     <th>Id</th>
     <th>Title</th>
     <th>Runner Name</th>
     <th>Staff Name</th>
     <th>Level</th>
     <th>Status</th>
      <th>View</th>
       </tr>
     </thead>

     <tbody>
     <?php foreach ($page->items as $emergencyreport): ?>
         <tr class="w3-hover-">
         <td><?php echo $emergencyreport->id ?></td>
         <td><?php echo $emergencyreport->header ?></td>

          <?php $runnername = Runner::findFirstByid($emergencyreport->runnerId);?>
         <td data-toggle="modal" data-target="#myModal<?php echo $runnername->id ?>"  ><a style="color: #0056b3"><?php echo $runnername->fname." ".$runnername->lname ?></a></td>

         <div class="container">
         <!-- Trigger the modal with a button -->
         <!-- Modal -->
         <div class="modal fade" id="myModal<?php echo $runnername->id ?>" role="dialog">
         <div class="modal-dialog">
           <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
         <div class="card">
         <div class="cover">
           <p class="ssid w3-padding w3-display-topmiddle">RUNNER</p>
           <img  class="rounded-circle photo w3-display-bottommiddle" src="../public/images/<?php echo $runnername->images ?>">
         </div>
         <p class="name"><?php echo $runnername->fname." ".$runnername->lname ?></p>

         <p>Gender : <?php echo $runnername->gender?></p>
         <p>Telephone number : <?php echo $runnername->tel?></p>
         <p>Nationality : <?php echo $runnername->nationality?></p>
         <p>Shirt : <?php echo $runnername->shirt?></p>
         </div>
         </div>
         </div>
         </div>


         <!--กล่อง pop up staffname -->
           <?php
           $staffname = Staff::findFirstByid($emergencyreport->staffId);?>
           <td data-toggle="modal" data-target="#myModal1<?php echo $staffname->id ?>"  ><a style="color: #0056b3"><?php echo $staffname->fname." ".$staffname->lname  ?></td>

           <div class="container">
           <!-- Trigger the modal with a button -->
           <!-- Modal -->
           <div class="modal fade" id="myModal1<?php echo $staffname->id ?>" role="dialog">
           <div class="modal-dialog">
             <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
           <div class="card">
           <div class="cover">
             <p class="ssid w3-padding w3-display-topmiddle">STAFF</p>
             <img  class="rounded-circle photo w3-display-bottommiddle" src="../public/images/<?php echo $staffname->images ?>">
           </div>
           <p class="name"><?php echo $staffname->fname." ".$staffname->lname ?></p>

         <p >Category : <?php echo $staffname->category ?></p>
           </div>
           </div>
           </div>
           </div>

           <td>

             <?php
             if($emergencyreport->level == 1){
               ?>
               <label class="star-rating" style="color:#ffbf00;;">  <i class="fa fa-star"></i></label>
               <?php
             }else if($emergencyreport->level == 2){
               ?>
         <label class="star-rating" style="color:#ff8000;">  <i class="fa fa-star"></i><i class="fa fa-star"></i></label>

               <?php
             }
             else{
               ?>
       <label class="star-rating" style="color:red;">  <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></label>
               <?php
             }

       ?>

           </td>

         <td><?php
         if($emergencyreport->status == 0){
           ?>
           <label style="color:red;">   <i class="fa fa-times fa-lg"></i> </label>

           <?php
         }else{
           ?>
             <label style="color:#53B12F;">   <i class="fa fa-check fa-lg"></i> </label>
           <?php
         }
         ?></td>

          <td><a href="/Marathon/marathon/emergencyreport/edit/<?php echo $emergencyreport->id ?>">View</td>
         </tr>
     <?php endforeach; ?>
     </tbody>


   </table>
</div>

<!-- เเถบเลื่อนหน้า -->
<div class="container">
    <ul class="pager">
      <li class="w3-btn " style="margin-left: 10px;">
          <?php echo $page->current, "/", $page->total_pages ?>
      </li>
     <a href="/Marathon/marathon/emergencyreport/search?page=<?php echo $page->next ?>"><li class="w3-btn w3-white w3-border w3-border-black  w3-round-xxlarge " style="float: right; color:white !important; background-color: black !important;"><h5> ></h5> </li></a>
     <a href="/Marathon/marathon/emergencyreport/search?page=<?php echo $page->before ?>"><li class="w3-btn w3-white w3-border  w3-border-black  w3-round-xxlarge w3-left" style="margin-left: -40px; color:white !important; background-color: black !important;" > <h5> <</h5>  </li></a>
 </ul>
</div>
</html>
