<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["emergencyreport", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create emergencyreport
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "emergencyreport/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldHeader" class="col-sm-2 control-label">Header</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["header", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldHeader"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDetail" class="col-sm-2 control-label">Detail</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["detail", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDetail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRunnerid" class="col-sm-2 control-label">RunnerId</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["runnerId", "type" => "number", "class" => "form-control", "id" => "fieldRunnerid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStaffid" class="col-sm-2 control-label">StaffId</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["staffId", "type" => "number", "class" => "form-control", "id" => "fieldStaffid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLag" class="col-sm-2 control-label">Lag</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["lag", "size" => 30, "class" => "form-control", "id" => "fieldLag"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLng" class="col-sm-2 control-label">Lng</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["lng", "size" => 30, "class" => "form-control", "id" => "fieldLng"]) ?>
    </div>
</div>



<div class="form-group">
    <label for="fieldLevel" class="col-sm-2 control-label">Level</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["level", "type" => "number", "class" => "form-control", "id" => "fieldLevel"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
